name: Cleanup Deleted Releases

on:
  schedule:
    # Run every hour to check for deleted releases
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install dependencies
      run: go mod tidy
      
    - name: Run cleanup script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: mburakmmm/wing-packages
      run: |
        go run scripts/cleanup-deleted-releases.go
        
    - name: Commit changes
      if: steps.cleanup.outcome == 'success'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add packages.json
        git diff --staged --quiet || git commit -m "Cleanup deleted releases from registry"
        git push
